# Generated by Django 3.0.3 on 2020-06-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizeapp', '0002_auto_20200619_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
